### ISSUE TITLE
Maple-Seed crashing at launch

### ISSUE THREAD

**Issue by ldaneels** [Tsume/Maple-Tree#10]
Hi, I couldn't find any info on this, so here it goes. When I launch MapleSeed, it crash instantly.
I use Windows 10. My CPU is a I7 4770K, I use a GTX 980. If you need more info, let me know.
Thanks,

Loic

**Comment by Catarax** [comment]
Same thing but crash during folder analyse http://image.prntscr.com/image/ead82a7d621c4355852cf456921050d0.png

**Comment by Tsume** [comment]
@ldaneels Is the meta folder present? If not, that's likely why it's crashing.

**Comment by Tsume** [comment]
Should be fixed.

**Comment by DDraiger** [comment]
I have this problem, I have tried all versions of maple

**Comment by haka3l** [comment]
Same problem on Windows 10 it gives crazy error after adding games folder and when it tries to scann it.
https://d3higte790sj35.cloudfront.net/images/rd/pd/cd954d9bb985ca673e2724f4868e91ef.jpeg

**Comment by Tsume** [comment]
This build should fix that null error.

https://pixxy.in/04I2262.zip

**Comment by skywotch** [comment]
my error it's this: i can do nothing ??

System.UnauthorizedAccessException: L'accès au chemin d'accès 'C:\Users\SkyWotch\AppData\Local\Application Data' est refusé.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   à System.IO.FileSystemEnumerableIterator`1.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   à MapleLib.Database.LoadLibrary(String titleDirectory) dans E:\Projects\MapleTree\MapleLib\Database.cs:ligne 401
   à MapleLib.Database.Load() dans E:\Projects\MapleTree\MapleLib\Database.cs:ligne 57
   à MapleCake.ViewModels.MainWindowViewModel.<OnLoadComplete>b__21_0()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à MapleCake.ViewModels.MainWindowViewModel.<OnLoadComplete>d__21.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.DispatcherOperation.InvokeImpl()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Threading.DispatcherOperation.Invoke()
   à System.Windows.Threading.Dispatcher.ProcessQueue()
   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Application.RunDispatcher(Object ignore)
   à System.Windows.Application.RunInternal(Window window)
   à MapleCake.App.Main()

**Comment by Tsume** [comment]
The errors not being in English kind of makes it difficult to read lol.

Have you tried the build above your comment? It may fix that issue.

**Comment by Tsume** [comment]
Oh. Make sure you're running MapleSeed as Admin. It requires write access to your user data directories.

**Comment by skywotch** [comment]
Yes sorry i'm french but your fix above my comment do the same error. When i run MapleSeed as Admin i have the error again. But when i delete cemu of my pc i don't have the error but when i instal it i have the error.

**Comment by Tsume** [comment]
What version are you using? I have no idea what you mean when you say you delete it you don't have the error.

Delete the directory "C:\Users\(user)\AppData\Roaming\MapleTree"

Your title directory is being set to a location you don't have access to. That's what's causing the error.

**Comment by skywotch** [comment]
1.7.4 for cemu and last version for mapleseed. i said when i delete cemu 1.7.4 i don' t have any error when i run mapleseed i can choose i file normal. in my "C:\Users\user", i don't have appdata folder.

**Comment by Tsume** [comment]
I need you to be more specific. What version are you using? Give me numbers. Numbers. 2.1.1.8, 2.1.1.7? Which one specifics?

Delete "C:\Users\SkyWotch\AppData\Roaming\MapleTree"

**Comment by skywotch** [comment]
The version of maple seed is 2.1.1.11. And i can't delete this file because in skywotch folder i don't have AppData folder.

**Comment by Tsume** [comment]
What version of Windows are you using?

**Comment by skywotch** [comment]
windows 10

**Comment by Tsume** [comment]
You're on Windows 10, and you don't have an AppData folder? I find that hard to believe. Either your Windows installation is extremely broke, or the folder is hidden. The folder is likely hidden. Insert that path into File Explorer's uri input. Without quotes.

**Comment by skywotch** [comment]
ok i try

**Comment by skywotch** [comment]
Don't working, windows don't find the folder

**Comment by Tsume** [comment]
Try this.
[MapleSeed2.zip](https://github.com/Tsume/Maple-Tree/files/913216/MapleSeed2.zip)

**Comment by skywotch** [comment]
It's working thx you i instal zelda breath of the wild 1.1.1

**Comment by rburggraf** [comment]
I am having the same issue.  It crashes immediately at launch.  I am running Windows 10 64bit
[error.log](https://github.com/Tsume/Maple-Tree/files/3268691/error.log)

**Comment by Tsume** [comment]
You’re using an outdated version of mapleseed. Recent releases are on the subreddit.
