### ISSUE TITLE
New error maple seed 2

### ISSUE THREAD

**Issue by Venn1** [Tsume/Maple-Tree#116]
Pls help I got this error when i tried to start Mapleseed2
![errorwtf](https://user-images.githubusercontent.com/31018473/29291379-f75229e8-8175-11e7-9c01-32fdc7f0e7c5.PNG)

**Comment by Tsume** [comment]
Open task manager and make sure MapleSeed2 isn't still running.

**Comment by x8lx8** [comment]
I am also getting this same error, Maple Seed 1 works fine

I made sure neither applications were running in task manager

**Comment by x8lx8** [comment]
Fixed it by deleting the "MapleTree" folder under:   Users / yourname / appdata / roaming

Just delete the "MapleTree" folder and run MapleSeed again as Admin

**Comment by x8lx8** [comment]
Shoot actually, I only got it to load the windows that allows you to select your game directory folder and the cemu.exe but it wont actually load MapleSeed2. Not getting an error, it just doesn't execute or something
