### ISSUE TITLE
MapleSeed2 Crash on Startup

### ISSUE THREAD

**Issue by Insayno** [Tsume/Maple-Tree#117]
![image](https://user-images.githubusercontent.com/22404521/30050399-598c34d8-91ec-11e7-9776-9081ba474695.png)

**Comment by Insayno** [comment]
Windows 10

**Comment by ortonomy** [comment]
mine too

**Comment by Tsume** [comment]
Browse to that location and delete mapleseed.db. Check to ensure mapleseed isn't running in the background by using Task Manager.
