### ISSUE TITLE
Uninstall doesn't work

### ISSUE THREAD

**Issue by lollo78** [Tsume/Maple-Tree#120]
Hi, if I hit Uninstall I have this error and crash:
https://pastebin.com/SF4sdQ1P

I deleted MapleSeed2.exe and clean the Windows registry but if I start it again I see the previous settings (game and esecutable path, games database list...). Where is located this information and how to manually delete it?

**Comment by Tsume** [comment]
That error says the database is already being used. Open task manager and make sure MapleSeed2.exe isn't running in the background.

The file can be found at C:\Users\user\AppData\Roaming\MapleTree

**Comment by Tsume** [comment]
I've worked out a few fixes for the errors thrown when using the Uninstall button.

**Comment by lollo78** [comment]
MapleSeed2.1.1.17-PRE-03.exe solve the Uninstall bug.
Thanks a lot
