### ISSUE TITLE
Updates finishing, but no folders created

### ISSUE THREAD

**Issue by Reidlos65** [Tsume/Maple-Tree#121]
BOTW updates finish according to log, but not creating the last folders.  Did this change?

looking again, its getting server errors so it maybe just giving up?  around content file 78 of 181 it keeps failing and not going past.

**Comment by Tsume** [comment]
If you're getting errors from the download server. It's more likely to be something on nintendo's end. You could try waiting to see if it resolves over time.

**Comment by Reidlos65** [comment]
ok ill see what happens later
