### ISSUE TITLE
MapleSeed 2.1.1.16-hf-1 crash

### ISSUE THREAD

**Issue by lollo78** [Tsume/Maple-Tree#123]
Hi, just downloaded MapleSeed Version 2.1.1.16-hf-1.
It crash on start with this error:
https://pastebin.com/Ur1BZaGS
Previous 2.1.1.16 works fine

EDIT:
To avoid the error I need to delete C:\Users\user\AppData\Roaming\MapleTree folder.
But it doesn't work. Library generation is very slow at every Mapleseed start and LAUNCH CEMU doesn't works.
The uninstall button continue to crash the app, like described here: https://github.com/Tsume/Maple-Tree/issues/120

**Comment by Tsume** [comment]
What kind of system are you running it on?

**Comment by lollo78** [comment]
Hi, 
Windows 10 Creators Update (v. 1703)

**Comment by Tsume** [comment]
There is a pre-release in the discord that should fix those issues. If it doesn't, please update me with any further errors.

**Comment by lollo78** [comment]
Thanks Tsumes, it works great but respect old MapleSeed release (like 2.1.1.14) the Library games appears slowly (quickly respect 2.1.1.16-hf-1, but not like 2.1.1.14).

I tried to uninstall and reisntall. All works fine, but I can't see anymore the "cache" folder inside "...AppData\Roaming\MapleTree" directory.

**Comment by felysu** [comment]
Hello! Just wanted to say that I had the exact same error popping up today (which is weird, I didn't install any windows update or anything and yesterday it was working). The build found in discord doesn't crash and seems to work fine!
