### ISSUE TITLE
Deleting missing title crashes and empties library

### ISSUE THREAD

**Issue by KytoDragon** [Tsume/Maple-Tree#127]
I accidentaly mistyped a title id and clicked download, chose "No" on the popup and fixed the typo to download the correct one. When i then chose the "Delete title" option of the incorrect game i got an exception message about trying to access an non-existing directory and the program crashed. On restart both titles (the wrong and correct ones) both vanished, though i could thankfully retype the title id and continue the download. This is problably just a case of checking if the folder actually exists before deleting it.

**Comment by Tsume** [comment]
I believe I've ran into this issue myself when debugging once. Thought I fixed it. I'll look into it and see if I can replicate it.
