### ISSUE TITLE
What The Hell Tsume? Virus??

### ISSUE THREAD

**Issue by BoTWFan** [Tsume/Maple-Tree#129]
v2.1.1.7 is stopped by SmartScreen, 2.1.1.6 won't let me update anything OR add DLC, and the zip file is suddenly undeleteable?? what's going on???

**Comment by Tsume** [comment]
The zip is a normal zip created by windows’ default built-in method. What kind of error are you getting exactly?

**Comment by BoTWFan** [comment]
It's not giving an error code, Windows SmartScreen is just blocking it. The previous version, 2.1.1.6, works until I try to update my game, then suddenly MalwareBytes shuts the program citing Some name I don't remember. I got it to work by going to MEGA and downloading 2.1.1.4 from some dude's setup pack.

**Comment by User239** [comment]
Norton and Windows both flag this as a virus for me

**Comment by Snadder** [comment]
Don't worry guys, it's just that SmartScreen can sometimes mistake an exe that will install something on your computer for a virus, happened to me a few times when I tried to install my GPU drivers directly from amd's website...
