### ISSUE TITLE
Error: this tool requires network connection

### ISSUE THREAD

**Issue by usuallee** [Tsume/Maple-Tree#132]
Hello, I'm having an issue that seems to be unique as I couldn't find anything on the interwebs. When using Mapleseed to grab updates & DLC, I get the following window: This tool requires internet connection for network features. 

![capture](https://user-images.githubusercontent.com/32989062/31855655-535886ce-b67d-11e7-9920-de67aff792c0.PNG)

Definitely have internet connectivity. Any ideas? I restarted my computer as an initial step but still doing it after reboot.
[mserror.log](https://github.com/Tsume/Maple-Tree/files/1404431/mserror.log)

Edit: When you click okay to the above, the program then crashes. 
Log file attached. Thanks in advance for any help.

**Comment by Snadder** [comment]
Try to run Mapleseed  as administrator because windows could be blocking access to internet that ( of course ) prevents it from downloading DLC and updates.

**Comment by usuallee** [comment]
Snadder, thanks for responding. Thanks for making this tool, it should be wonderful once I get it working. I did in fact try running as administrator, with no joy.

So just FYI, I tried the previous version, 2.1.1.16, and it seems to be working so far. Two things were different when running 2.1.1.16 as opposed to 2.1.1.17. First, Windows asked if I really wanted to run the program, it said invalid certificate or something. I said yes. Second, my Webroot SecureAnywhere security suite asked me if I wanted to allow Mapleseed to connect to the internet. I again said yes. NEITHER of those things happened when trying to use 2.1.1.17 -  I got neither of those prompts. I had also tried manually adding an exception for Mapleseed in Webroot, no luck.

Maybe it is a peculiarity of my particular set up, but Windows 10 as well as Webroot certainly reacted differently (i.e., didn't react at all really) to 2.1.1.17 as opposed to 2.1.1.16, which elicited behavior more normal on my system when firing up a new app for the first time. 

Hope this helps, it certainly didn't seem like anyone else had had this issue so maybe it is my system but it seems 2.1.1.17 has been changed somehow which resulted in different behavior compared to the previous version.

**Comment by Snadder** [comment]
I didn't make this tool, Tsume did. I don't actually use the latest mapleseed as I myself has issues with it ( made a thread about it too) so the best one that has worked for me so for is mapleseed 1 ( the version of mapleseed that released after mapleseed light), so you could try using that version as it works as it should at least.

**Comment by Tsume** [comment]
The certificate errors may be related to CDecrypt. It's compiled differently in 2.1.1.17.

The only reason the network error would appear is if for some reason it can't access google.com. That's literally all it does, try to connect to google. If it can't, you see the error. It could be dns related or something blocking it.

**Comment by YawningSheep** [comment]
I'm having the same issue, but rolling back to the previous version, 2.1.1.16, did not work. I have a wired Ethernet connection, I've added the program to my security software as allowed, and I've tried every version currently available on the site. Any ideas?

**Comment by Tsume** [comment]
If anyone is still experiencing this, feel free to update this issue.

**Comment by SirInfern0** [comment]
I'm experiencing this same problem on 2.1.1.18. Could firewall be acting up with it? Also, I've just kind of restarted the program whenever I have this issue and it seems to continue to download. I have a feeling that the download is going to be corrupted.
