### ISSUE TITLE
Add an option to disable controller support

### ISSUE THREAD

**Issue by Stalaw** [Tsume/Maple-Tree#135]
Trying to play a game with a controller with Mapleseed open will result in constantly being tabbed out by CEMU launching every time you press A. Please add an option to disable controller support.

**Comment by Tsume** [comment]
Added this in commit f34fd57  

Should be in the next update.

**Comment by Tsume** [comment]
Added in the following update: https://github.com/Tsume/Maple-Tree/releases/tag/2.1.1.18
