### ISSUE TITLE
Mapleseed stops working after I select my extract directory.

### ISSUE THREAD

**Issue by Layrun** [Tsume/Maple-Tree#140]
I was following a guide to setup zelda and in this step, I get this error and I don't know what to do here.
I select the directory where my games are extracted but then I get this error.
Here is a screenshot of it: https://puu.sh/yphYW/1a978a0b73.png

**Comment by Tsume** [comment]
Try using this version: 
[MapleSeed2.1.1.19-PRE.zip](https://github.com/Tsume/Maple-Tree/files/1485661/MapleSeed2.1.1.19-PRE.zip)

You may be using an older version. The .19 pre also has some built in error reporting that'll help me diagnose the issue better.  Make sure to run MS again after it crashes.

**Comment by Layrun** [comment]
I tried using your version but it doesn't do anything when I open it. Nothing opens.

I opened it after it crashed and this is what I got: https://puu.sh/ypkI3/5224193337.png

**Comment by Tsume** [comment]
Have you tried using Version 2? Version 1 hasn't been updated in months.

Make sure dot net 4.5.2 and 4.6 are installed.
