### ISSUE TITLE
Mapleseed2 crashed! please help..

### ISSUE THREAD

**Issue by shimguemin** [Tsume/Maple-Tree#142]
i try to delete appdata/Mapletree but it doesn't worked

[error.log](https://github.com/Tsume/Maple-Tree/files/1497248/error.log)

what can i do??

경로에 대한 액세스가 거부되었습니다 = process Access is denied

**Comment by Tsume** [comment]
Which version of MS are you using?

**Comment by shimguemin** [comment]
win10
