### ISSUE TITLE
Mapleseed 1.1.0.53 and 2.1.1.18 crash ''Title Database is empty. This should not happen!!!''

### ISSUE THREAD

**Issue by YumanC** [Tsume/Maple-Tree#143]
Hello. I am getting an error in both versions of Mapleseed after selecting my Cemu directory. Mapleseed immediatly crashes at startup. The weird is I don't remember having this error in my previous installation of Windows 7. Also the log specifies an ''E:'' path E:\Projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:line 33 , but I never selected E: as my directory for Cemu. What's going on?

Mapleseed 1.1.0.53 crash log: https://pastebin.com/DsfXP0ct
Mapleseed 2.1.1.18 crash log: https://pastebin.com/mQGs4Tqg

**Comment by shiningnight** [comment]
same here

**Comment by Tsume** [comment]
What's the output you're getting from this url? http://api.pixxy.in/title/count
.18 pulls the title count from that url it should never return 0 unless it's not reading for some reason.

**Comment by YumanC** [comment]
It says ''2498''.

**Comment by Tsume** [comment]
Delete the following location and try running it again.

C:\Users\user\\AppData\Roaming\MapleTree

**Comment by JRBarnett21** [comment]
I am getting the same message. I am on a Windows 7 machine and do not see a AppData folder.

**Comment by JRBarnett21** [comment]
I am trying to open the Mapleseed v1. v2 I don't have a problem eith.

**Comment by JRBarnett21** [comment]
nvm. It ended up being hidden. I found it.
