### ISSUE TITLE
Cannot Start Application 

### ISSUE THREAD

**Issue by viltis-projekt** [Tsume/Maple-Tree#17]
can't open the program after updating, here's my log file
[18Y23P1O.log.txt](https://github.com/Tsume/Maple-Tree/files/836600/18Y23P1O.log.txt)

**Comment by Tsume** [comment]
What version are you using?

**Comment by viltis-projekt** [comment]
maple seed latest  edge

**Comment by Tsume** [comment]
That doesn't help. Which version specially?
