### ISSUE TITLE
Since 1.1.0.35 I have in my "Dashboard"-Tab games multiple times

### ISSUE THREAD

**Issue by Maufeat** [Tsume/Maple-Tree#18]
Updated to 1.1.0.35 and with the Dashboard-Tab I have now every game 6 times except Zelda, it is there 12 times.
![test](https://cloud.githubusercontent.com/assets/3602392/23854903/d71379c6-07f3-11e7-8d93-c69bd96c517f.png)

**Comment by Tsume** [comment]
I just spotted this on my test client. A fix will be out later today. Likely in an hour or two.

**Comment by Tsume** [comment]
Should be fixed for versions 1.1.0.37+
