### ISSUE TITLE
Maple Seed fails to start if no titles currently exist

### ISSUE THREAD

**Issue by klusark** [Tsume/Maple-Tree#19]
Issue was introduced in this commit
https://github.com/Tsume/Maple-Tree/commit/d0cb91a9b5b99cb298ffa3bf3fb273f0495d2120

The issue is caused by this line in 1Form1.cs:
await SetCurrentImage(Database.TitleDb.Values.ToArray()[0]);

TitleDb is empty, so [0] is out of bounds

**Comment by Tsume** [comment]
Thanks for that heads up.

It'll get fixed today.

**Comment by Tsume** [comment]
Fixed as of commit 3d21fad
