### ISSUE TITLE
Does not find 2 games

### ISSUE THREAD

**Issue by Edmiller99** [Tsume/Maple-Tree#20]
Maple Seed does not find 2 games Project Zero Maiden Of Black Water  and Rodea The Sky Soldier

**Comment by Tsume** [comment]
Make sure they both have a meta folder and a meta.xml file present. WUD/Wux formats are no longer supported prior to version 1.1.0.40

**Comment by Tsume** [comment]
There was a bug fix that should have fixed this issue. If not let me know.
