### ISSUE TITLE
High DPI issues

### ISSUE THREAD

**Issue by AmineI** [Tsume/Maple-Tree#21]
Hi ! On windows, using a big screen with DPI scaling won't scale most of the software.
Here's a screenshot with the github page in background, to compare.
![capture3](https://cloud.githubusercontent.com/assets/15179425/24080814/ab6319a0-0ca6-11e7-9443-f972cd42ba46.PNG)

Do you think you can do something about it ? 
Thank you for your time !

**Comment by Tsume** [comment]
I'll look into unifying the sizing on higher DPI displays.

**Comment by SamusAranX** [comment]
If it's not too much work, you could try switching to a WPF-based GUI.
WPF isn't as garbage as WinForms and correctly scales all elements for you, even across differently-scaled monitors.

**Comment by Tsume** [comment]
A new UI is already in the works as of 5b8a540d41481d174453b20dfe918807b5b220b0. I plan on having it ready for release in a few weeks.

**Comment by Tsume** [comment]
Version 2 released a few days ago. Which shouldn't have dpi issues.
