### ISSUE TITLE
Integration with cemu_graphic_packs

### ISSUE THREAD

**Issue by VictorHartman** [Tsume/Maple-Tree#23]
In theme of automating the process of adding games. These graphic packs are very useful for every game and it's still a manual process.

see here: https://github.com/slashiee/cemu_graphic_packs

maybe this could be implemented with git?

**Comment by Tsume** [comment]
This was already in the works prior to this, but since it's here.

Add as of commit c73bc6c169d6a3e1446bae3a913564a89208ed7e
