### ISSUE TITLE
MapleSeed2 has lost nearly all of my games from its database.

### ISSUE THREAD

**Issue by Trudovah** [Tsume/Maple-Tree#237]
### Version Used
Mapleseed2, V 2.1.1.18

### Expected behavior
Launch MS2, expect to see list of MK8, BoTW and LoZ W.W.

### Actual behavior
Launch and only W.W. is present in games list

After updating BoTW and adding DLC, it has disappeared from my games list on Mapleseed. I can still launch an play it from CEMU, but it's less stable now and doesn't hold the frame rates like it did before. 
MK8 did the same thing, but I care less about that game...haha. 

I changed the folder file path for my games, that didn't help. I uninstalled and reinstalled MS2, still no help. I run it under admin (always). 
Not sure what to do here.

any help would be awesome. 
Thanks!

**Comment by Tsume** [comment]
Is there a log file present you could upload? Make sure the library path hasnt changed.

**Comment by Trudovah** [comment]
Here is the message it gives me in the Log....
I think I may have figured it out. I am currently downloading the title id through Mapleseed2...I'll update after it finishes...

![maplelog](https://user-images.githubusercontent.com/33711883/34341104-668e094e-e95e-11e7-9851-9ec981f51ca8.jpg)

**Comment by Tsume** [comment]
Oh, forgot to note. Those ID's it's failing to locate are updates(I think), or maybe DLC. Either way, it won't load titles detected as either an update or DLC.
