### ISSUE TITLE
Problem with botw 1.1.1

### ISSUE THREAD

**Issue by Noodlesteak** [Tsume/Maple-Tree#24]
When I started the game after I downloaded  it with Maple seed (the seed I used was 00050000101c9400)
cemu told me "Wii u need an update, please come back to menu" And of course I can't start the game.
(before it worked with the 1.1.0)

**Comment by Tsume** [comment]
Right click the title then update it.

**Comment by Noodlesteak** [comment]
ok I start this and I tell you if it works for me :)

**Comment by Noodlesteak** [comment]
THANKS a lot it worked ! :)
