### ISSUE TITLE
Maple seed only opens once

### ISSUE THREAD

**Issue by Kushcabbage** [Tsume/Maple-Tree#25]
I installed maple seed 2.1.1.8 to the root of a hard drive and it only opened the first time after I installed it. When I try and open it after that the icon appears on the taskbar and in task manager but no window appears.
Windows 8.1 cemu 1.7.3

**Comment by UncleVesimir** [comment]
@Kushcabbage  - Whilst I have no idea why this issue occurs, I ran into this myself. Something that worked for me...

If you go to your main directory, find the 'Users' folder, AppData (this is a hidden folder, here's help on showing them - 
[Show hidden folders - MS Support](https://support.microsoft.com/en-gb/help/14201/windows-show-hidden-files)) and then go to Roaming. Here you should find a folder called 'MapleTree'. Delete this.

Re-run MapleSeed. Hopefully this should work.

An example of my file path to AppData\Roaming:

 C:\Users\James\AppData\Roaming

**Comment by Kushcabbage** [comment]
Deleting the appdata worked, but mapleseed stops working every time I set up the cemu and title folders and close.

**Comment by komawoyo** [comment]
The program current seems to have problem parsing `MapleSeed.ini` once that is fix, everything should load up correctly

**Comment by Tsume** [comment]
Paste the contents of your .ini configuration.

**Comment by nicomda** [comment]
Same for me. Just crashes when trying to load graphic pack database... or that's what indicates the log. I paste my .ini info.

> [MapleTree]
CemuDirectory = C:\Users\Nicomda\Desktop\cemu174_bdd0f93007627b3
TitleDirectory = C:\Users\Nicomda\Desktop\cemu174_bdd0f93007627b3\The Legend of Zelda Breath of the Wild [ALZP01]
DynamicTheme = False
StoreEncryptedContent = True
CacheDatabase = False
FullScreenMode = False
GraphicPacksEnabled = False

**Comment by Tsume** [comment]
Try this:

Change TitleDirectory to C:\Users\Nicomda\Desktop\cemu174_bdd0f93007627b3

Change CacheDatabase to True

**Comment by nicomda** [comment]
I tried that but doesn't work. I've also renamed folder name to cemu174 to avoid errors and set cemu and TitleDirectory to that folder. CacheDatabase is set to True in .ini file.

**Comment by Tsume** [comment]
So, it just hangs/crashes there? No errors?

Try this build. If it doesn't work, it should at the very least output an error I can trace. Screenshot the error that appears.

https://pixxy.in/kTu0257.zip

**Comment by nicomda** [comment]
Here it is the screenshot.
![captura](https://cloud.githubusercontent.com/assets/4690565/24704187/d6f9405e-1a06-11e7-9cc3-a595c1807e28.JPG)

**Comment by Tsume** [comment]
Run this one, it should still crash, but will output a error.log file. If it does, send me that file.

https://pixxy.in/nCJ1260.zip

**Comment by nicomda** [comment]
I've been working around. I'm on W10 Bootcamp and donna why cannot access to wiiu.titlekeys(dot)com are you using it? Gonna try through VPN because on OSX I've access to the web without any problem.

**Comment by nicomda** [comment]
Solved. The problem was something related to dns on the network I'm connected now. I've used the app through OpenVPN and that solved the error. So the crash was due to non resolving wiiu.titlekeys maybe you should handle connection error exception to avoid the crash.

**Comment by Tsume** [comment]
Awesome!!, now that I know that, I can add a fix for it.

Thanks. :)

1. PreCached Json DB

**Comment by Gallieg444** [comment]
I am having this same issue still. Exactly as described. I am going to try a vpn now...
