### ISSUE TITLE
MapleSeed 2 -  "Uninstall" greyed out in Win10 apps/programs, uninstalling requires running initial installer again

### ISSUE THREAD

**Issue by RanceJustice** [Tsume/Maple-Tree#26]
I recently downloaded MapleSeed 2 and installed it, but I've noticed a number of issues, not the least of which is that  I see no easy way to uninstall it!   

I'm using MapleSeed 2.1.1.8  on Windows 10 Pro (latest updates).  Installing it went fine, but when I go to the normal Windows system application management,  MapleSeed is present but both the "Modify" and "Uninstall" buttons are greyed out and clicking on the entry does nothing. For reference, this is not a system wide issue as other applications have their uninstall buttons present and active.     Likewise, there is also no uninstaller written into the MapleSeed install directory as some programs have, thus providing the frustrating element that it is not possible to uninstall at current.    If there is another way to properly and completely uninstall MapleSeed 2 please let me know, but I hope this issue can be resolved.  Thank you. 

Edit: Other issues include MapleSeed2 not apparently having an easy way to re-pick the games directory, and it seems that the program recognizes by Bayonetta(US) loadiine-ready install in its own folder within my games directory, but NOT my disc-ripped, compressed .wux format Twilight Princess HD (US) in a similar folder in the same directory. Does the program not support .wud/.wux formatted games by design? If so, that would be a good thing to state prominently.   I'd be happy to make individual issues entries for these issues if it would be helpful. Thank you. 

Edit2: I was able to install be running the original MapleSeed 2 installer file itself again on a whim and selecting "remove", so it is nice it was able to be uninstalled, but this method is a bit cumbersome so it would nice for users to be able to uninstall it like any other program directly from their OS's typical application management area, it at all possible.  If it is not possible or very difficult, then please include a notification in the FAQ that the users must keep the original installer to uninstall it for any reason. Thanks!

Thank you for your work on this new utility that should help CEMU users greatly!

**Comment by Tsume** [comment]
I can't imagine why it would be disabled, and was going to suggest using the installer, but I see you figured that out already. I'll see about writing up removal tool to make the process easier in the future.

It does not have support for wud/wux, and chances are it never will.

AppData ->Roaming -> MapleTree, deleting that directory will effectively remove it from your system.
