### ISSUE TITLE
Maple Seed 2.1.1.8 Doesn't load any titles.

### ISSUE THREAD

**Issue by Breaker12** [Tsume/Maple-Tree#27]
I have been wating for quite some time but Maple Seed doesn't load any titles.

**Comment by Tsume** [comment]
Take a look at the Log and see if any errors are being thrown. If none, close the app, delete the folder located at. C:\Users -> (Username) -> AppData -> Roaming -> MapleTree, then try again.

Make sure there are no special characters in any of your directory paths, Only letters and numbers. Also make sure all of your game titles have a meta/meta.xml file.

**Comment by Kushcabbage** [comment]
Mapleseed detects my games that are "in folders" but not .wud or .wux files

**Comment by Tsume** [comment]
@Kushcabbage It's not supposed to.
