### ISSUE TITLE
Maple seed huge chash log

### ISSUE THREAD

**Issue by FkYuFkeverything** [Tsume/Maple-Tree#283]
### Issue Checklist
- [ ] Meet Requirements [Here](https://github.com/Tsume/Maple-Tree#requirements)
- [ ] Read FAQ [Here](https://github.com/Tsume/Maple-Tree#faq)

### Version Used
Example: 2.1.1.18

### Expected behavior
Work
### Actual behavior
doesn't even load
[error.log](https://github.com/Tsume/Maple-Tree/files/1594730/error.log)

### Steps to reproduce behavior
1.?
2.?
3.?

**Comment by Tsume** [comment]
It's failing to complete a SSL connection to github.
