### ISSUE TITLE
Some titles deasapear after update games

### ISSUE THREAD

**Issue by lanner** [Tsume/Maple-Tree#29]
Hello
I have some title games who desapear from the list after copy the files to update, i have the meta.xml in all games
No errors on "log" and i have try to delete the folder in roaming
Thanks

**Comment by Tsume** [comment]
If you're overwriting your game folders that is why.

**Comment by lanner** [comment]
i have copy the 3 folders to update the game , that's not what i have to do ?

**Comment by Tsume** [comment]
If you're using Cemu 1.7.3+ with MapleSeed, you don't have to move any folders that are downloaded, they're automatically placed in the correct directory.
