### ISSUE TITLE
error, whats that mean?

### ISSUE THREAD

**Issue by Parktronis** [Tsume/Maple-Tree#30]
On 1.7.3 and 1.7.4 had this error http://image.prntscr.com/image/24ee98417dc247c6bc03d665e7de3d30.png
I downloaded and updated without problems, but when I launch, I see an error

**Comment by komawoyo** [comment]
hmmm... read it... it says that you need to UPDATE!!!!!!!!!!!!!!

**Comment by Parktronis** [comment]
Well, how do you then explain that the last version I downloaded via "wii usb helper" was launched without this error,
In both cases, I downloaded the dlc and last update v48, but game from wii usb helper work. from maple NO

**Comment by Parktronis** [comment]
Well, how do you then explain that the last version I downloaded via "wii usb helper" was launched without this error,
In both cases, I downloaded the dlc and last update v48, but game from wii usb helper work. from maple NO

**Comment by Tsume** [comment]
This is a simple case of using MS incorrectly. 8 out of 10 people start using it wrong, not bash in any way, just a statement. This is closed off simply because I don't like repeating my self. If Wii U USB Helper works for you, have at it.

**Comment by Parktronis** [comment]
I downloaded and updated without a single error (Maple Seed), and I used the Wii USB to see what the problem was, not because I did not like MapleSeed.
But since I am advised to "read and update", I do not need such help
And I had no choice but to look for help elsewhere and I was helped with a Wii u usb helper. Although I do not like this program

**Comment by Tsume** [comment]
A new version was released a few minutes ago, you should try it out to see if you still have the same issues.
