### ISSUE TITLE
can't connect to server 

### ISSUE THREAD

**Issue by theRealFakeRock** [Tsume/Maple-Tree#32]
I get a long error that starts with "Unable to connect to the remote server". I have tried a couple of different things like deleting the app data, making a firewall rule, and running as administrator. Is the server down?

**Comment by ChrisEickelman** [comment]
Same issue here, I set the cemu.exe location, set game directory, and after 30 seconds or so this error pops up (pics attached)

![library](https://cloud.githubusercontent.com/assets/9989963/24691920/b446ae58-1a19-11e7-8256-e474dbf06e00.png)
![log](https://cloud.githubusercontent.com/assets/9989963/24691924/b8455c66-1a19-11e7-928e-e8a66795b80e.png)

Also notice in the first pic (library tab) it is trying to do something with "E:\Projects" - this folder used to exist a few weeks ago, but when I moved my projects to a different drive I deleted this folder.

**Comment by theRealFakeRock** [comment]
same

**Comment by Kazanna** [comment]
Getting the same issue, and besides the Game Directory folder text (Because mine is in my "C:\CEMU\Games" folder) it's the same to the letter.

**Comment by ChrisEickelman** [comment]
Seems to be resolved!

**Comment by Tsume** [comment]
A new version has been uploaded with bug fixes left and right. Try it out and respond to this issue thread if you're still having the same issues.
