### ISSUE TITLE
Suggestion: DLC names

### ISSUE THREAD

**Issue by Felina-Lain** [Tsume/Maple-Tree#336]
MapleSeed2 is amazing when it comes to downloading update, but with how the interface is right now, it's not as good for DLC
For games with multiple DLC for exemple, you can't know which one you have, are downloading, or uninstalling...

Adding the dlc name to the drop menu would be solving this...

**Comment by Tsume** [comment]
If I recall correctly, I considered this originally and ran into issues with pulling separate DLC from N servers. I'll make a note to look into again.
