### ISSUE TITLE
Scan for additional games format

### ISSUE THREAD

**Issue by komawoyo** [Tsume/Maple-Tree#34]
Hello, 

This is to request support additional formats such as the compressed wud -  *.wux file extension 
Game updates should work as expected

Directory Setup is as followed
```
GameDir\*wux
GameDir\Mario Kart\code
GameDir\Mario Kart\content
GameDir\Mario Kart\meta
```

**Comment by Tsume** [comment]
I'll consider it. Maybe.

**Comment by komawoyo** [comment]
Yeah, I have taken a quick look at the code, the only issue would be extracting the titleId from the *.wux files for it to be integrated into Database.cs. Everything else should remain the same besides the one line change in Toolbelt.cs to grab *.wux extension. 

I'll see if there's an easy way - unless there's a predefined naming format
Currently, I have "[GAME NAME]_[titleKey]" such that 
```
Tank! Tank! Tank! (US)_6EFF589114DCC07E9AA4CA9417B0AA30.wux
```
Maybe I'll just add a quick and dirty fix to grab the titleId in the name to compare with the json database.

**Comment by Tsume** [comment]
The major thing that's prevented me from adding support for those formats is the inability to read said files during runtime at a reliable pace. I haven't figured out how to read those formats at all actually, and I won't do it in a quick/fix type of way. It's bad practice.

So long story short. Don't look forward to this, it's unlikely to happen. But if it does, it'll likely be weeks if not months from now.

**Comment by Tsume** [comment]
What I could do instead of add a way for users to input their own custom formats using the file name as data points.
