### ISSUE TITLE
Crash at the opening

### ISSUE THREAD

**Issue by dylink** [Tsume/Maple-Tree#35]
I think that I've set a wrong file for the scan of games, and since this, I can't even run the .exe, it crashes at the begining, deleting the program doesn't fix anything

**Comment by Tsume** [comment]
It still amazes me how many ways people have found how **not** to use what should be an extremely simple tool.

C:\Users\(user)\AppData\Roaming\MapleTree

Delete that directory.

**Comment by dylink** [comment]
The problem is that, the program asks where are the games, so I selected the root file where my games are, I didn't thought that I should have selected file directly

**Comment by Tsume** [comment]
If you're still experiencing crashes, upload the error.log file it generates. If it doesn't generate one, then get the latest version from the releases page.
