### ISSUE TITLE
Invalid characters in the acces path

### ISSUE THREAD

**Issue by LordViperagyil** [Tsume/Maple-Tree#37]
when I try to use Maple seed 2 to setup Botw in CEMU it crashes with the massage in the title. The path of Cemu is desktop/emulator/cemu_1.7.4d while the rom is in desktop/emulator/cemu:1.7.4d/roms. the error logis in hungarian unfortunetly.
[error.docx](https://github.com/Tsume/Maple-Tree/files/908109/error.docx)

**Comment by Tsume** [comment]
Invalid characters in the access path. Pretty straight forward. Check your directory and game paths to make sure they don't include special characters. This is a Window limitation, I'm surprised you even have a directory with : in the path.
