### ISSUE TITLE
BOTW asks for update after updating to tlates version

### ISSUE THREAD

**Issue by Tasosgemah** [Tsume/Maple-Tree#370]
### Version Used
2.1.1.18

After updating the game and downloading the DLC with Mapleseed the game no longer loads. It now says "You must perform a system update to play Zelda:BoTW" How do i do that?

**Comment by KytoDragon** [comment]
Also using 2.1.1.18, same Problem. Updated the game to v160 and then installed the new DLC.

**Comment by SalamanderSandwich** [comment]
DLC->Update to 112->set all version.txt and AOCversion.txt to 1.3.1
You'll get a warning but you'll be able to change the voice.
