### ISSUE TITLE
Mapleseed error when trying to download a file

### ISSUE THREAD

**Issue by caiowb** [Tsume/Maple-Tree#371]
### Issue Checklist
- [ ] Meet Requirements [Here](https://github.com/Tsume/Maple-Tree#requirements)
- [ ] Read FAQ [Here](https://github.com/Tsume/Maple-Tree#faq)

### Version Used
2.1.1.18

### Expected behavior
Download title after confirming message box

### Actual behavior
Crashes upon clicking Okay

### Steps to reproduce behavior
1.??
2.???
3.???
[error.log](https://github.com/Tsume/Maple-Tree/files/1682316/error.log)

**Comment by Tsume** [comment]
I keep seeing this error being brought up, but can't seem to pinpoint it. It's noted, so I'll get it fixed eventually(hopefully). The error logs don't say much in the way of what the actual issue is. Makes it that much harder to find.
