### ISSUE TITLE
Update errors. Updater not working now!

### ISSUE THREAD

**Issue by cakama3a** [Tsume/Maple-Tree#374]
### Version Used
MapleSeed Version 2.1.1.18

A month ago everything worked well, but now when updating Zelda a lot of notifications are coming, Update does not work. That's what the log writes ... http://prntscr.com/ikltz9

**Comment by zeroepoch** [comment]
Probably same as #375

**Comment by Tsume** [comment]
Is  it possible you could get those error displayed in english? would help diagnose the problem.
