### ISSUE TITLE
SSL/TLS Error with .NET Framework 4.6.2

### ISSUE THREAD

**Issue by Bertrand-A** [Tsume/Maple-Tree#375]
### Issue Checklist
- Nothing in FAQ

### Version Used
Mapleseed : 2.1.1.18 and 2.1.1.19pre
OS : Windows 10 Enterprise LTSB 2016 (1607) build 14393.2097, x64 System
.NET : 4.6.2 (Full version : 394802) (see : https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

### Expected behavior
- On right click on a game : Can select Update and download it (v160, v192, etc)

### Actual behavior
- Right click on a game : We can see **only** the  "[+] DLC" button and main button freeze on "LOADING..."
- In Logs tabs, there is a exception about SSL/TLS error : "The request was aborted: Could not create SSL/TLS secure channel"
- Impossible to update a game.
- It seems that the guilty are .NET Framework Updates, but I'm not sure (I don't know very well .NET Framework environment)

### Steps to reproduce behavior
1. Upgrade your Windows 10 for the latest one (Home, Pro, Enterprise, etc)
2. Launch MapleSeed2.exe (with Administrator privileges)
3. Look at the Logs or the Main window.

There are many subjets about it (not for MapleSeed but for C# devs)
Example : https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

I can add screenshots if you ask.
Thanks for your investigations.
Sani.

**Comment by zeroepoch** [comment]
I'm also seeing this same behavior on Windows 10 the latest version.

**Comment by Bertrand-A** [comment]
Yes, Wii U USB Helper can download and decrypt additional content, but the main objective is to resolve this issue.
I tried to run it on a Win8.1 Pro on my Hyper-V, the error persists.

An other solution is to put all websites called into HTTPS procotol instead of HTTP. 
Tsumes offered me his help (source code of mapleseed API), and i'll try to make some tests on my personnal website (with HTTPS protocol and valide SSL certificate).

I'll keep you informed.

**Comment by N3dStark** [comment]
Hy,

i have the same problem. Have you found solution ?

**Comment by mgreter** [comment]
Adding the suggested fix from the linked stackoverflow answer into GraphicPackDatabase.cs (line 40) seems to do the trick! [Recompiled with VS 2017 and it now shows `[Title Database] Loaded 2498 entries`](https://github.com/Tsume/Maple-Tree/files/1827533/MapleSeed2.exe.zip).
```diff
  string dataString;
+ System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls12;
  if ((dataString = await Web.DownloadStringAsync("https://github.com/slashiee/cemu_graphic_packs/releases/latest")) == null)
```

**Comment by Tsume** [comment]
Seems to fix the issue. It'll be in the next release.

**Comment by 0xW1sKy** [comment]
I dont see anything in the releases yet that include this fix so for those like me looking for a solution in the meantime, you can run this via powershell:

# set strong cryptography on 64 bit .Net Framework (version 4 and above)
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

# set strong cryptography on 32 bit .Net Framework (version 4 and above)
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
