### ISSUE TITLE
Major Error With Most recent Version of Maple Tree.

### ISSUE THREAD

**Issue by Devilswarchild** [Tsume/Maple-Tree#376]
im just dropping an error log here cause for some reason Tsumes hasnt added me on discord yet.
[error.log](https://github.com/Tsume/Maple-Tree/files/1821971/error.log)

**Comment by Tsume** [comment]
Thanks. I’ve been extremely busy. New daughter. Job. Life. I’ll try to fit in some time to squash some bugs. There’s a bit of a list left.

**Comment by Devilswarchild** [comment]
Yeah you should add me on Discord so that I can communicate problems to you faster cause of you leaving the REGNR8 server I can nolonger message you without being your friend.

**Comment by Tsume** [comment]
My name on discord is Tsumes#9310, feel free to add me.

**Comment by Devilswarchild** [comment]
youll need to add me Devilswarchild#8913

**Comment by Devilswarchild** [comment]
and the reason I say that is because I have tried to send you a Friend request on discord but you have incoming friend requests disabled.
![screenshot_1](https://user-images.githubusercontent.com/27385258/40688061-5c8270ba-6362-11e8-805c-f0e84c8871a6.png)
