### ISSUE TITLE
 it does not work

### ISSUE THREAD

**Issue by Pologx** [Tsume/Maple-Tree#377]
### Issue Checklist
- [ ] Meet Requirements [Here](https://github.com/Tsume/Maple-Tree#requirements)
- [ ] Read FAQ [Here](https://github.com/Tsume/Maple-Tree#faq)

### Version Used
2.1.1.18

### Actual behavior

Does not show games and in the log appears this(attached image)
![sin titulo](https://user-images.githubusercontent.com/38161366/38456693-ceda1b64-3a5d-11e8-99a3-c7edb75a3086.png)

### Steps to reproduce behavior
1.Open the program on windows 10 with the latest version of cemu.

**Comment by Tsume** [comment]
This has been addressed in a recent commit and will be in the next release.

https://github.com/Tsume/Maple-Tree/issues/375
