### ISSUE TITLE
New Version of CEMU incompatibility.

### ISSUE THREAD

**Issue by Enigma2442** [Tsume/Maple-Tree#378]
### Issue Checklist
- [ ] Meet Requirements [Here](https://github.com/Tsume/Maple-Tree#requirements)
- [ ] Read FAQ [Here](https://github.com/Tsume/Maple-Tree#faq)

### Version Used
Example: 2.1.1.18

### Expected behavior
When trying to use program to download DLC and Updates, a list of updates are shown as well as DLC +

### Actual behavior
Many supported games (BotW, SM4SH, SuperMario3dWorld, etc.) are now showing they only have V0 as updates using the newest version of CEMU (1.11.6)
### Steps to reproduce behavior
1. Open mapleseed2
2. right click on selected game
3. proof.

**Comment by Tsume** [comment]
There's an underlying issue causing your problem. Title updates aren't dependent on Cemu's version. They're pulled from a remote database that has to be manually maintained.

Visit the website below. Type in the title ID of the title you wish to see versions for. See if it comes up correctly. You can also update them if they're out of date.
http://api.pixxy.in/

**Comment by wouax** [comment]
Hello,

I have exactly the same issue, for all my games
![image](https://user-images.githubusercontent.com/39044635/39687356-6280a176-51ce-11e8-9b04-51b13d4a95d2.png)

For zelda on your link I have that:
![image](https://user-images.githubusercontent.com/39044635/39687414-a6fc9648-51ce-11e8-84ee-f7e02eafd312.png)
