### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by tirrorex** [Tsume/Maple-Tree#38]
Hi
So, there is no instruction whatsoever on how to run it?
Should the project be compile and if with what tool?
Thanks

**Comment by PFCKrutonium** [comment]
Download a Release, or compile using Visual Studio. It's a C# project, after all.

**Comment by Tsume** [comment]
I'll update the readme to include more detail on how to get it running. The releases link on GitHub, is a lot smaller then it used to be and people overlook it. A lot, like, a LOT a lot lol.

The .zip is usually the compiled version.
https://github.com/Tsume/Maple-Tree/releases/tag/v2

**Comment by tirrorex** [comment]
Yup i didn't see the release link.
Thanks for the answers guys
