### ISSUE TITLE
Can't update BOTW

### ISSUE THREAD

**Issue by Walord06** [Tsume/Maple-Tree#380]
### Issue Checklist
![capture 2](https://user-images.githubusercontent.com/38965569/39608655-4532e0a8-4f43-11e8-872c-2157d043f0b9.JPG)
![capture](https://user-images.githubusercontent.com/38965569/39608656-454d774c-4f43-11e8-912d-e8dbb07b45b4.JPG)

### Version Used
2.1.1.18

### Expected behavior
Update Zelda BOTW

### Actual behavior
The update button is missing when i right click on my file. I also noticed that MS says that graphics pack are not available.

### Steps to reproduce behavior
1.Load MS
2.Rigth click on Zelda BOTW File

**Comment by Tsume** [comment]
I explained that error in issue #381
