### ISSUE TITLE
Graphic Packs Not Available

### ISSUE THREAD

**Issue by Dillmonger** [Tsume/Maple-Tree#382]
Graphic Packs have failed to load. Error states "[Graphic Packs] Error: Not Available". Full log cannot be copied, so I took screenshots for you to review.
![screenshot 7](https://user-images.githubusercontent.com/34577789/39672456-4300eed6-50df-11e8-8673-e6bf5a7692b0.png)
![screenshot 9](https://user-images.githubusercontent.com/34577789/39672457-46b7130c-50df-11e8-8372-5da4abdd2c1f.png)

**Comment by Tsume** [comment]
Search for ssl connection in the issues search box on github. There is a fix available in a previous issue ticket.   
  

  
  

  
  
>

**Comment by SebastianSosa** [comment]
Hi,

I have the same issue, but cannot find ssl connection issue in any box github project. Can you provide a link?

Thanks

**Comment by Walord06** [comment]
https://github.com/Tsume/Maple-Tree/issues/381
