### ISSUE TITLE
Games not loading in library

### ISSUE THREAD

**Issue by samiscool51** [Tsume/Maple-Tree#383]
### Issue Checklist
- [✓] Meet Requirements [Here](https://github.com/Tsume/Maple-Tree#requirements)
- [✓] Read FAQ [Here](https://github.com/Tsume/Maple-Tree#faq)

### Version Used
2.1.1.19 (i know, i will explain later in this issue report)

### Expected behavior
For games to load with the ability to access extra options like downloading updates and DLC

### Actual behavior
ok here we go,
i noticed that version 2.1.1.18 had a SSL connection error as explained in issue #381 and there was a pre-release version available to download, i downloaded that and no longer got any SSL problems but games still don't appear, the log doesn't show anything that could be of use
i know some dumb ass deleted the BOTW entry for the database as said in issue #381 and i am also wondering if it has been restored? i don't know if this project is still in development because the last update was 13 days ago (11/05/2018 (D/M/Y)) and that was for README.md

### Steps to reproduce behavior
1.execute said version of maple seed
2.have maple seed try and load said games
3. have it fail
4. become sad that it didn't work, many tears were shed on that day...

**Comment by Tsume** [comment]
I havent restored it yet. I actually forgot to. Oops. That being said. I can’t recall where i put the backup. I should have time to get it done later today though.   
  

  
  

  
  
>

**Comment by feikname** [comment]
All working fine now apparently 👍

**Comment by Tsume** [comment]
Yup. I restored the db yesterday and locked public editing. Should resolve some recent issues.

**Comment by samiscool51** [comment]
OK, big update
1. my anti-virus is thinks mapleseed is a "Machine Learning/Anormalous.96" threat (never heard of something like this, must be a new virus category), i think something in the code is triggering it, i have tried contacting them about the false positive but they haven't responded
2. more games are affected than just BOTW, i tried Wind Waker and Maple seed didn't detect it,
either something is wrong with the database (or something relating to it) or i am unable to connect up to it and receive the entry's
i think this should be a higher priority as this looks to be a very bad bug

**Comment by samiscool51** [comment]
can we re-open this issue as i'm still not getting anything
i downloaded wind waker and unfortunately it doesn't appear in the library
i checked both my title directory and CEMU directory and both were correct
either i am unable to connect to the database or it's still broken
i rebuilt it 2 mins ago and there is still nothing in the libary
is there a debug mode i can access as the log doesn't say there is anything wrong (quite helpful)
why is my life so hard....

**Comment by feikname** [comment]
@samiscool51 I believe this is a CEMU bug and not a MapleSeed issue, since mine also doesn't show any games in my library besides Wind Waker even though I configured it correctly. 

As a workaround, load the game manually with File->Load->Wind Waker folder->code->The rpx file (cking.rpx?)

**Comment by feikname** [comment]
Actually, deleting the game path and adding it again in CEMU seems to reload the game library on it.

However, games that are the same but with different regions (e.g. JPN and USA) seem to count as the same.
