### ISSUE TITLE
Certain games not being found in Maple Seed game directory

### ISSUE THREAD

**Issue by kbachert** [Tsume/Maple-Tree#398]
### Issue Checklist
- [X] Meet Requirements [Here](https://github.com/Tsume/Maple-Tree#requirements)
- [X] Read FAQ [Here](https://github.com/Tsume/Maple-Tree#faq)

### Version Used
2.1.1.18, and a few prior versions

### Expected behavior
Library of all my Wii U games in the folder specified

### Actual behavior
3 of my 7 games appear in the file list
The 3 that work are all .rpx files
The 4 that don't work are either .rpx or .wud files

### Steps to reproduce behavior
1. Install Maple Seed
2. Add folder with all my games to Maple Seed directory
3. Add Cemu directory
4. Library fails to find 4 games

**Comment by Tsume** [comment]
wud files are a compressed format and are not compatible. Don't really have any intention on adding support for that format as of yet. MS is being completely rebuilt. All issues related to versions released prior will be closed, as I won't be supporting it much longer.
