### ISSUE TITLE
Why is this program opening Google home page before every download it does?

### ISSUE THREAD

**Issue by DarthJahus** [Tsume/Maple-Tree#400]
So I was curious to see where the program was downloading stuff from and analyzed its traffic with Telerik's Fiddler. What I noticed is at multiple times, pretty much before or after every download, the program queries Google website. No research is done, it's just the home page. Is this some kind of debug stuff that remained unchanged?

**Comment by Tsume** [comment]
Oh. Now that I think about it. If you were referring to MS v1 and or v2. Google is used as a point of reference to verify active connections.
