### ISSUE TITLE
crash error when opening mapleseed 2.1.1.18 

### ISSUE THREAD

**Issue by mexmatic** [Tsume/Maple-Tree#401]
System.NullReferenceException: The object reference was not defined as an instance of an object.
   in MapleLib.Database. <> c__DisplayClass33_0. <FindTitle> b__0 (Title x) in E: \ projects \ MapleTree \ MapleLib \ Database.cs: line 106
   in System.Linq.Enumerable.WhereListIterator`1.MoveNext ()
   in System.Collections.Generic.List`1..ctor (IEnumerable`1 collection)
   in System.Linq.Enumerable.ToList [TSource] (IEnumerable`1 source)
   in MapleLib.Database.FindTitle (String id) in E: \ projects \ MapleTree \ MapleLib \ Database.cs: line 106
   in MapleLib.Database. <> c__DisplayClass34_0. <FindTitleAsync> b__0 () in E: \ projects \ MapleTree \ MapleLib \ Database.cs: line 116
   at System.Threading.Tasks.Task`1.InnerInvoke ()
   in System.Threading.Tasks.Task.Execute ()
--- End of stack trace from the previous location where the exception was issued ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult ()
   in MapleLib.Database. <FindTitleAsync> d__34.MoveNext () in E: \ projects \ MapleTree \ MapleLib \ Database.cs: line 116
--- End of stack trace from the previous location where the exception was issued ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult ()
   in MapleLib.Databases.WiiuTitleDatabase. <LoadLibraryForeach> d__10.MoveNext () in E: \ projects \ MapleTree \ MapleLib \ Databases \ WiiuTitleDatabase.cs: line 87
--- End of stack trace from the previous location where the exception was issued ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore. <String> c. <ThrowAsync> b__6_0 (Object state)
  in System.Windows.Threading.ExceptionWrapper.InternalRealCall (Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen (Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.DispatcherOperation.InvokeImpl ()
   in System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext (Object state)
   in System.Threading.ExecutionContext.RunInternal (ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run (ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run (ExecutionContext executionContext, ContextCallback callback, Object state)
   in MS.Internal.CulturePreservingExecutionContext.Run (CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Windows.Threading.DispatcherOperation.Invoke ()
   in System.Windows.Threading.Dispatcher.ProcessQueue ()
   in System.Windows.Threading.Dispatcher.WndProcHook (IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean & handled)
   in MS.Win32.HwndWrapper.WndProc (IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean & handled)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation (Object o)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall (Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen (Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl (DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   in MS.Win32.HwndSubclass.SubclassWndProc (IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   in MS.Win32.UnsafeNativeMethods.DispatchMessage (MSG & msg)
   in System.Windows.Threading.Dispatcher.PushFrameImpl (DispatcherFrame frame)
   in System.Windows.Threading.Dispatcher.PushFrame (DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher (Object ignore)
   in System.Windows.Application.RunInternal (Window window)
   in System.Windows.Application.Run (Window window)
   in System.Windows.Application.Run ()
   in MapleCake.App.Main ()

Mapleseed shows me this code when I try to launch it, somebody help?

**Comment by felipeapj** [comment]
I have the same issue
