### ISSUE TITLE
MapleSeed CLI Version 1.0b - DLL Not Found Issues

### ISSUE THREAD

**Issue by mohanen** [Tsume/Maple-Tree#406]
There are lot of dll seems to be missing in my pc. 
It would be great if you add what are the dependencies  to be installed before

**Comment by mohanen** [comment]
As per @Tsume  
The pre-release version contains the debug build. Which requires the debug version of vc_redis dll. 
And for LIBEAY32.dll download openssl
 
I attached the release build from Tsume with LIBEAY32.dll which should work fine with the normal 2017  [vc_redist.x64.exe](https://support.microsoft.com/en-in/help/2977003/the-latest-supported-visual-c-downloads)  




[MapleSeed.zip](https://github.com/Tsume/Maple-Tree/files/3036831/MapleSeed.zip)

**Comment by Tsume** [comment]
Not an expert at library linking, but if I'm not completely mis-understanding something, this build shouldn't require .DLL files to be present with it.
[MapleSeedCLI.zip](https://github.com/Tsume/Maple-Tree/files/3036856/MapleSeedCLI.zip)
