### ISSUE TITLE
Crashes when I try to open MapleSeedCLI.exe

### ISSUE THREAD

**Issue by Kakaka999** [Tsume/Maple-Tree#407]
LIBEAY32.dll error happening..

**Comment by StuMccly** [comment]
bump

**Comment by Tsume** [comment]
You shouldn't need libeay32. Are you using the build from the releases section?

**Comment by StuMccly** [comment]
assets, may be a case of user error in my case, redownloading

**Comment by BrockPereira** [comment]
Also getting the same error, using the build from the releases section.

**Comment by Kakaka999** [comment]
yeah, downloaded the latest release 1.0.1, tried downloading from other browser but still the same..

**Comment by StuMccly** [comment]
yeah, same, downlaoded release, libeay32 error

**Comment by Tsume** [comment]
Does that error appear when it first starts or when decrypting?

**Comment by BrockPereira** [comment]
When it first starts

**Comment by Tsume** [comment]
Try this build.

[MapleSeed++_x64D.zip](https://github.com/Tsume/Maple-Tree/files/3054965/MapleSeed%2B%2B_x64D.zip)

**Comment by Kakaka999** [comment]
it opens, thanks. The gui seems not to work though. Still I think I can use it.

**Comment by Tsume** [comment]
> it opens, thanks. The gui seems not to work though. Still I think I can use it.

Great.
The GUI doesn't have features yet.
