### ISSUE TITLE
Error during updating: "List that this enumerator is bound to has been modified"

### ISSUE THREAD

**Issue by VictorHartman** [Tsume/Maple-Tree#41]
I get this error often/always when updating Breath of the Wild. However the update succeeds and there doesn't seem to be a problem.

![untitled](https://cloud.githubusercontent.com/assets/6608079/24955356/599601ba-1f83-11e7-9483-f181bb11ac1c.png)

using version 1.1.0.53

**Comment by Tsume** [comment]
MapleSeed Version:
Error.log contents:

**Comment by VictorHartman** [comment]
Version number is given. I can't find an error.log file.

**Comment by Tsume** [comment]
Sorry about that, didn't see it.(mobile)

I'll be releasing an update for Version 1 later this week that should fix that issue. I've been compounding fixes for Version 1, and just haven't gotten around to finishing them off.

**Comment by VictorHartman** [comment]
I noticed that version 1 was not being updated as much as version 2, so this is great news.

**Comment by Tsume** [comment]
ver 1.1.0.51 was released, let me know if it still has the same issue.
