### ISSUE TITLE
Clicking Download in Content does Nothing MapleSeed++

### ISSUE THREAD

**Issue by TerrinX** [Tsume/Maple-Tree#422]
Nothing pops up, that about it

**Comment by TerrinX** [comment]
![Untitled](https://user-images.githubusercontent.com/55068613/80257231-6e0ae400-864e-11ea-9b1c-d00d3becef52.png)

**Comment by Tsume** [comment]
You’re missing the database. Should be able to grab one from another release.

**Comment by TerrinX** [comment]
I'm not exactly sure how to do that it even where to find previous versions
