### ISSUE TITLE
Trying to update WInd Waker HD but getting an error.

### ISSUE THREAD

**Issue by Isov91** [Tsume/Maple-Tree#44]
I have started the game and made a save point. When I try to update the game I get the following error. But the game is playable.

It's the USA version  and version is v0

![2017 04 17-18 32](https://cloud.githubusercontent.com/assets/15370243/25095522/57541d84-239c-11e7-9325-8ce95bbb2b30.png)

**Comment by Tsume** [comment]
Remove the TM character from the directory.

**Comment by Isov91** [comment]
I don't really know how access that name file because the map main folder doesnt have that TM in it. And I don't know where to find the name code in the files the map contains

**Comment by Tsume** [comment]
Which title id were you using?

**Comment by Isov91** [comment]
Not sure what youre meaning but if you mean "keys.txt" Im using key  "3cd545e19bbcb54e41db3169f7432ea1" which is for USA region.

**Comment by Isov91** [comment]
Hey I updated my Mappleseed version and used clean title and redownloaded it. After the title finishing downloading I got this first message error.  

![2017 04 22-17 50](https://cloud.githubusercontent.com/assets/15370243/25305956/cd2b8128-2784-11e7-8ce0-b48c239e9794.png)

**Afterwards when I tried updating the game again I got this different error code.** 

![2017 04 22-17 50_01](https://cloud.githubusercontent.com/assets/15370243/25305962/ed69159a-2784-11e7-9e7d-f469ca18b728.png)

**This is the game directory. What do I progress from here?**

![2017 04 22-17 53_01](https://cloud.githubusercontent.com/assets/15370243/25305976/0d8062de-2785-11e7-8131-36670e3b09b4.png)

**Comment by Tsume** [comment]
Those two errors can be ignored, they don't stop the process from completing successfully. Or shouldn't. They'll be fixed in a future update for Version 1.

The accented A in your directory paths is what's causing the issue. The program doesn't have support for those characters yet. Sorry.
