### ISSUE TITLE
Issue when start application

### ISSUE THREAD

**Issue by darksouf33** [Tsume/Maple-Tree#49]
On the first boot I choose the 2 folder and then I have the following error in capture http://imgur.com/a/sG0qY . The error remains the same after deleting the MapleTree folder in AppData \ Roaming \ MapleTree

Win7 64 French
Cemu 1.7.5
MapleSeed Version 2.1.1.12 and MapleSeed Version 1.1.0.52  same issue

**Comment by Tsume** [comment]
You should be able to ignore that error. A fix is already(or should be) implemented in a recent commit.

The fix will be included in the next update.
