### ISSUE TITLE
Graphics pack selected changes when you switch between games

### ISSUE THREAD

**Issue by Noodlefu** [Tsume/Maple-Tree#50]
I looked over the code briefly and I understand this information isn't saved, but every time you select a game the drop down list selects a random pack rather than a previously selected one. I understand you wan't to add the ability to launch with multiple packs enabled - if that's the case then this might well be on your TODO list already, but figured there's no harm in making the issue known.

**Comment by Tsume** [comment]
This has been in the back of my mind since I first implemented it.  Won't make any promises, but I'll try to get this out along with the next update. It'll require a bit more work then other additions. So it may not happen until later.

- [ ] Implemented saving selected graphic pack

**Comment by Tsume** [comment]
Implemented as of commit 714ce2030669c4ce972389589645f764ddd8385e

It will be included in the next update.
