### ISSUE TITLE
On CEMU 1.7.5 after updating BotW using MapleSeed 2.1.1.12, the game freezes at the loading screen

### ISSUE THREAD

**Issue by knwt** [Tsume/Maple-Tree#53]
On CEMU 1.7.5 after update BotW to the newest version using MapleSeed 2.1.1.12, the game freezes at the loading screen after selecting a save game.

I've read some other people with this problem and apparently MappleSeed is pulling a new update for Zelda Breath of the Wild(v80) that is broken.

The only way for me to play the game is to ask mapleseed to delete the update. But I'm back to the vanilla BotW.

**Comment by brainygamer** [comment]
I'm having the same issue, exactly as described by knwt. I love MapleSeed. Hope this can be worked out soon.

**Comment by Tsume** [comment]
You'll have to use version 1 to apply a manual update until I add that feature into version 2. I didn't intend to ever add it to v2. But never forsaw this to be a potential issue. I'll try to get a new version out this week.

**Comment by brainygamer** [comment]
Thanks for the quick response, Tsume. And many thanks for MapleSeed.

**Comment by knwt** [comment]
Thank you!

**Comment by Tsume** [comment]
This has been added to version 2.1.1.13, which I plan on releasing after a bit of testing.

There will be a small textbox under the control panel tab where you can set the version you which to update to or download.
