### ISSUE TITLE
MAPLE SEED 2.11.12 NOT WORKING

### ISSUE THREAD

**Issue by kilyan82** [Tsume/Maple-Tree#54]
If i try to open the program, nothing happens, it doesn't even ask for game directory. The previous version, 1.1.0.52  works,
So no idea what is the issue?!
Windows 10 pro 64 is my O.S.
I found the log file of the error, hope it  helps
[Report.zip](https://github.com/Tsume/Maple-Tree/files/975766/Report.zip)

**Comment by Tsume** [comment]
Try using the most recent version 2.
https://github.com/Tsume/Maple-Tree/tree/v2.1.1.12

**Comment by kilyan82** [comment]
i'm using the latest, 2.1.1.12, i forgot to put a dot after the second 1 in the title of this thread

**Comment by Tsume** [comment]
Make sure you're running MapleSeed2.exe.

MapleSeedU2.exe is an older version that shouldn't work.

**Comment by kilyan82** [comment]
Yep as i said, i'm using the latest, see the icon screenshot on my desktop attached
![cattura](https://cloud.githubusercontent.com/assets/28387126/25775060/889f1524-329c-11e7-9477-a2238e11f671.JPG)

**Comment by kilyan82** [comment]
redownloaded, and now seems to work O_O
no idea

**Comment by Tsume** [comment]
2.11.12 had a number of re-uploads due to bug fixes.

**Comment by kilyan82** [comment]
i see , thanks
