### ISSUE TITLE
Riva tuner statics server conflict with mapleseed2

### ISSUE THREAD

**Issue by kilyan82** [Tsume/Maple-Tree#55]
I found out the reason why mapleseed2 didn't work for me! had nothing to do with the version of the software: it was riva tuner statics server preventing it to open. Closing it, the mapleseed2 software starts normally.
Version 1 of mapleseed works also with riva tuner statics server open, so would be nice if also mapleseed2 worked with riva tuner statics server opened.

**Comment by Tsume** [comment]
This issue has be brought to me directly a few times, and it's something I can't fix. The creators of Riva Tuner would need to rework the way their software detects D3D9 applications, as it incorrectly detects WPF applications It's not specific to MS, but to WPF as a whole.

You should be able to add an exception for specific programs. At the moment that would likely be the best route going forward. If something comes up that suggests there's something I can do on my end to fix this specific issue please feel free to comment here and I'll re-open/look into it.
