### ISSUE TITLE
Issue, I can't open.

### ISSUE THREAD

**Issue by Kappachido** [Tsume/Maple-Tree#56]
![captura de pantalla 6](https://cloud.githubusercontent.com/assets/28544854/25823884/bc054ec2-343d-11e7-99aa-b8c2540f37c9.png)
![captura de pantalla 7](https://cloud.githubusercontent.com/assets/28544854/25823885/bee2f31a-343d-11e7-9128-7925cba5873d.png)

**Comment by Tsume** [comment]
Try to use version .13
