### ISSUE TITLE
mapleseed2 2.1.1.13 wrong game version

### ISSUE THREAD

**Issue by kilyan82** [Tsume/Maple-Tree#57]
The software doesn't recognize game version, says 0 nd should be 64. And says there is no update, when there shoud be one, the 80 version. Maybe i do something wrong?
![2 1 1 13](https://cloud.githubusercontent.com/assets/28387126/25894386/df28a752-357b-11e7-8f4c-1e5a100de06b.jpg)

**Comment by Tsume** [comment]
The built in database it uses is out of date. Go to the Control Panel and input the version number in the small text box before clicking update.

I plan on fixing issues like these in the future when I rework the database.

**Comment by kilyan82** [comment]
i confirm this way it works, but need also to put title id of the game
