### ISSUE TITLE
Not all games in the folder are recognised.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [Tsume/Maple-Tree#59]
Thanks a lot for all your efforts you are putting into this :)

The issue I have is that not all games in the folder are recognised (MapleSeed 2.1.1.13). For example:

- G:\Games\Emu\_Roms\Wii-U\Donkey Kong Country Tropical Freeze (USA)\WUP-P-ARKE\data\code\rs10_production.rpx

- G:\Games\Emu\_Roms\Wii-U\Mario Kart 8 (EUR)\Mario Kart 8 (EU).wux

I'm not Windows 10 x64 with the latest Creator Update.

Thanks.

**Comment by Tsume** [comment]
Wud and wux formats are not currently supported in MS. 

For donkey Kong make sure meta/meta.xml exists. it's required for title detection.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Ah, that explains it. I do seem to miss a few metas. Thanks :)
