### ISSUE TITLE
Mapple Seed closes entirely when closing Share prompt window

### ISSUE THREAD

**Issue by darkdrifter** [Tsume/Maple-Tree#6]
Everything is in the title :)

When I close the prompt to locate my Cemu installation after clicking on the Share button, the application close entirely instead of just closing the prompt.

EDIT: Not just on the Share button but everytime the locate Cemu prompt displays.

**Comment by Tsume** [comment]
It's supposed to close. Are you hitting anything other then the OK button?

**Comment by darkdrifter** [comment]
Yeah, I pressed the cross.

**Comment by Tsume** [comment]
It's currently that way intentionally to avoid issues. The cemu base directory is parsed based off the executable. If it doesn't know the cemu directory, things will break.
