### ISSUE TITLE
Add Progress Status/Bar for Downloads?

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [Tsume/Maple-Tree#60]
Hi,

Would it be an idea to add a Progress Status/Bar? With also some sort of message/sound when it's done.
I know that we can also see it from the log window, but that's not so obvious.

Also, I think that "Log" is a bit of a technical term and isn't really inviting for people to click on, in general. Although it's quite essential to the program.
Renaming it to "Progress" would make it a more accessible term and thus option for more people.

**Comment by Tsume** [comment]
I don't plan to make any further changes to the UI outside of bug fixing. What you see is more or less what will be for the foreseeable future.

It's called Log because that's what it is. It also displays non-fatal errors.
