### ISSUE TITLE
Status on right-click not automatically updating.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [Tsume/Maple-Tree#61]
Hi,

When right-clicking again after downloading a(n) update/DLC, the info like version and the "-" option is not updated. Could you please refresh that after a download?

Thx

**Comment by TheStruggleForAntiSpaghetti** [comment]
After writing the issue, I right-clicked again and now it's updated. Could it be that it's updated not right away but after a while?

**Comment by Tsume** [comment]
It's working as intended. But the update trigger for the context menu is... lacking when compared to Version 1. For now it works well enough to focus on optimizing and fixing current issues. I'll return to UI optimization after the current Milestone.
