### ISSUE TITLE
Indication in main list for various statuses.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [Tsume/Maple-Tree#62]
Hi,

Would it be possible to see in the main list right away the various statuses like is now shown when right-clicked? Things like current version number and available update version number, if available DLC is downloaded or not. Could be just text.

Thx.

**Comment by Tsume** [comment]
Version 2 is meant to be a minimalized version of 1. Although I would like to add progress bars under each title when downloading relevant content. I don't expect I'll be making any changes to the UI anytime soon.

That said, I'll look into adding more image based information once I feel optimization of the current code is complete.
