### ISSUE TITLE
Mapleseed wont run correctly

### ISSUE THREAD

**Issue by ImCthu1hu** [Tsume/Maple-Tree#63]
I keep getting an error message whenever the application is trying to load up. It then causes it to crash and close the program down. 

error message-  http://imgur.com/a/oCQYX

**Comment by Tsume** [comment]
I've seen this exact error more times then I can count.

How did you go about setting your directory as the recycle bin?

**Comment by ImCthu1hu** [comment]
I have no idea. That happened the first time I opened the application. However now when I open the application it says d:/System volume information instead of $recycle bin. I've tried uninstalling and completely removing all files from mapleseed and even wiping the system recovery files and re-downloading everything and it still isn't working.

**Comment by Tsume** [comment]
It looks like you're using an older version of MS. Are you using V1 or V2?

Browse to the following location.
C:\Users\(user name)\AppData\Roaming\MapleTree
Delete all files under that directory and try to run MS again.
