### ISSUE TITLE
Nothing happens after choosing title directory and executable

### ISSUE THREAD

**Issue by Andrew497** [Tsume/Maple-Tree#68]
Using most recent version (2.1.1.14) but have tried 2.1.1.13 with deleting MapleTree folder in appdata and restarting in between. With both versions the program shows up for a few seconds in task manager after choosing the launch options but then disappears and nothing happens. Not using any vpn, and have tried with security software turned off.

**Comment by Cannasteve** [comment]
I have the same issue, i have just download cemu 1.8.0b and the last version of Mapleseed 2.1.1.14 ( and my old version of Mapleseed2 with cemu1.7.5 doesn't work anymore too), i have delete the folder Mapletree in C:/Users/XXX/Appdata/Roaming folder and all mapleseed entries in the  Windows 10 registry.
I have used once the old version for update Zelda botw 1.0.0 to 1.1.1 i would try update to 1.1.2 or 1.2.0

**Comment by kilyan82** [comment]
guys disable any overlay you have running and it will work,check also if game dvr is active and disable it if on windows 10

**Comment by Andrew497** [comment]
Disabling game dvr worked, thanks so much!

**Comment by kilyan82** [comment]
no problem, i had the same issue and found out that was the problem.
I think should be done a sticky message saying that mapletree doesn't work if any overlay is on. Less troubleshooting to do for the admin :D

**Comment by Cannasteve** [comment]
Thank you so much, i have disable MSI Afterburner,  Riva Tuner Statistics Server and HWinfo64, Gamedvr was already disable. I haven't read the FAQ sorry
