### ISSUE TITLE
Force Rebuild Database download failure

### ISSUE THREAD

**Issue by Elvtin** [Tsume/Maple-Tree#70]
When I select the option to do the Force Rebuild Database I get the error in the screen show below.

![image](https://cloud.githubusercontent.com/assets/15043686/26666622/ef888028-466e-11e7-8c6e-abee05df0bf4.png)

I'm pretty rookie with Mapleseed so I imagine i'm actually doing something wrong or not understanding what this function is supposed to do. 
I did add the Mapleseed EXE to my firewall exception just in case it was getting blocked but that didn't resolve the issue.

**Comment by Tsume** [comment]
Use version 2.1.1.14
