### ISSUE TITLE
Failed to download DB

### ISSUE THREAD

**Issue by codrak2** [Tsume/Maple-Tree#71]
I get this error everytime, I saw someone posted this error and the solution was using a newer version of mapleseed, but I am on that version.

I already tried deleting the mapleseed appdata folder, and still the same issue.

![imagen](https://cloud.githubusercontent.com/assets/29137828/26711755/a205be34-4730-11e7-9f67-e9b53c68201c.png)

**Comment by Tsume** [comment]
Try going to both of those URLs in your web browser. I've heard that some ISP block those addresses. Which may be the case. It won't stop the core program from working, but it will lock you into the current state of the database. All-in-all, it really shouldn't effect the usage much.

**Comment by readyplayer4** [comment]
hey tsume, i keep getting the same error,nothing seems to be happening at all,cant even see how i am meant to update my botwplease advise?

**Comment by Tsume** [comment]
Could you screenshot the exact error you're getting?

**Comment by readyplayer4** [comment]
![screenshot 1](https://user-images.githubusercontent.com/31738422/30225529-b719d958-94ca-11e7-834e-430e471830c8.png)
![screenshot 3](https://user-images.githubusercontent.com/31738422/30225530-b7273120-94ca-11e7-93c9-c2c862b65f2b.png)
![screenshot 5](https://user-images.githubusercontent.com/31738422/30225531-b7309c88-94ca-11e7-8649-f216444043a1.png)
![screenshot 6](https://user-images.githubusercontent.com/31738422/30225532-b73aabf6-94ca-11e7-9e54-e9f958f1695a.png)
the first is the error i get when i try using the latest version,i then tried downloading the update anyway after typing the code,the download starts but keeps failing at about no.45,so i stopped trying and went back to one of the older versions.the subsequent images are the errors i get on the older versions, as you can see it just fails on the start up and i really dont know what else to do man.thanks for the help.
