### ISSUE TITLE
NullRefrenceException error

### ISSUE THREAD

**Issue by shashankjakhmola** [Tsume/Maple-Tree#72]
![capture](https://cloud.githubusercontent.com/assets/29173481/26760152/53361fdc-492f-11e7-886c-9dfa0146a90a.PNG)

Using the latest version of Maple to update Breath of the Wild. 

What am I doing wrong?

**Comment by shashankjakhmola** [comment]
![capture](https://cloud.githubusercontent.com/assets/29173481/26760190/f4af04d2-492f-11e7-8b5c-216fcc93903a.PNG)
It's still downloading the update, but I'm not sure if it'll work.

**Comment by Tsume** [comment]
Looks like it failed when attempting to create the GraphicPack array. Error is too vague to say why. It won't effect the content download though.

**Comment by shashankjakhmola** [comment]
Well, the game shows the version 1.2.0.0 so I suppose it worked.

**Comment by Tsume** [comment]
I'll be looking into this error today. Can't promise I'll resolve the exact issue, but it shouldn't throw that error in the next update.

**Comment by jennygreene88** [comment]
I get this same error immediately upon launch, and fatally, on the latest releases of both 1.1 and 2.1.
