### ISSUE TITLE
Mapleseed 2 Crashing at Launch

### ISSUE THREAD

**Issue by Jetpoo** [Tsume/Maple-Tree#73]
Running Windows 7 on Bootcamp.
Attempting to run Mapleseed 2.1.1.14 as administrator and it is crashing at launch.
Tried searching in C:\Users\User1\AppData\Roaming and there is no mapleseed folder

Any idea how to resolve this issue?
Thank you!

Event Viewer is showing two errors:
1---
Faulting application name: MapleSeed2.exe, version: 2.1.1.14, time stamp: 0x59270dfe
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23796, time stamp: 0x59029714
Exception code: 0xe0434352
Fault offset: 0x000000000001a06d
Faulting process id: 0xfe0
Faulting application start time: 0x01d2dd87df1b6f1d
Faulting application path: C:\Users\User1\Desktop\MapleSeed2 (1)\MapleSeed2.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 1ead92b5-497b-11e7-8f23-3c15c2cf8b4d

2---
Application: MapleSeed2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at MapleCake.App.Main()

**Comment by Tsume** [comment]
Make sure it meets the requirements. Outside of that, I can't help you with virtual machines, since I don't have one to debug on.

**Comment by Jetpoo** [comment]
Thanks for the feedback. Where can i read up on the requirements?
DO you think i'd have better luck on Windows 10?

**Comment by Tsume** [comment]
The README on the main page.
https://github.com/Tsume/Maple-Tree/blob/master/README.md
