### ISSUE TITLE
Mapleseed 2 crashes upon opening with this error

### ISSUE THREAD

**Issue by otakukj** [Tsume/Maple-Tree#76]
![mapleerror](https://user-images.githubusercontent.com/10216811/27767516-92e71a4c-5f2c-11e7-8bc9-008fac25ffb8.png)

**Comment by dsherwood9** [comment]
Same thing happened to me and I don't know how to fix it

**Comment by Tsume** [comment]
There is a update that hasn't been publicly released yet that should reduce/remove that error, though it may not fix the underlying issue. (yet).

**Comment by otakukj** [comment]
Great! Thanks for the reply! When is the public release? Any ETA yet?

**Comment by Tsume** [comment]
Most likely sometime this week.

**Comment by otakukj** [comment]
Fantastic! Thank you very much  for the quick reply. I hope that this contribution can help others with similar issues.

**Comment by straylightrun89** [comment]
fixed for me as of update 5 minutes ago. fantastic work!

**Comment by ortonomy** [comment]
Hi @Tsume -- this is still happening to me, both versions of Mapleseed. Exactly the same error about not being able to find a file at users/.../appdata/mapleseed/graphicsPack.

Any ideas?

**Comment by Tsume** [comment]
Could you post a screen shot of the exact error?

**Comment by ortonomy** [comment]
@Tsume -- I've opened a new issue here (https://github.com/Tsume/Maple-Tree/issues/118)  for [Mapleseed 1.1.0.5] bug.
