### ISSUE TITLE
New error appearing

### ISSUE THREAD

**Issue by esplec** [Tsume/Maple-Tree#77]
I used mapleseed the first time to update BotW to 1.2.0 and DLC 1.0. It worked perfectly with CEMU 1.8.0b; now I upgraded to 1.8.1b and I want to get the Master Trials DLC but I can't, because Mapleseed will give me this error. [http://imgur.com/a/7qw2K](http://imgur.com/a/7qw2K)

**Comment by otakukj** [comment]
Link to your picture didn't work just FYI

**Comment by esplec** [comment]
Copy the link and paste it in the search bar.

**Comment by Tsume** [comment]
I honestly don't know what to make of that error. Make sure dot net 4.6 is installed.

**Comment by dass2** [comment]
esplec- i got it the same error did you fixit.
