### ISSUE TITLE
Issue downloading content

### ISSUE THREAD

**Issue by leopoldodonato** [Tsume/Maple-Tree#79]
Hi,
I have a problem with both versions of MapleSeed.
Very often, when I'm downloading, the download get stuck and, even if I wait for hours, it won't make any progress (I checked and it looks that my connection is active every time).
Sometimes, if i close Maple Seed and reopen it, the download fails and the log show 'An exception occurred during a WebClient request', other times the download continue only to get stuck a few moments later.
I have .NET Framework 4.7 installed and disabled firewall.
Do you have any solution for this issue?

**Comment by Tsume** [comment]
Sounds like a general bad connection. That'll be less of an issue once I manage to implement download resuming. The most you could do now probably stop/pause all other downloads/network activity when downloading large files.

**Comment by leopoldodonato** [comment]
Thank you!
I'll look forward download resuming function, hoping things get better.


2017-07-05 14:39 GMT+02:00 Tsume <notifications@github.com>:
