### ISSUE TITLE
BOTW I only see v16 and v33

### ISSUE THREAD

**Issue by KathrynCrawford** [Tsume/Maple-Tree#84]
![untitled](https://user-images.githubusercontent.com/10589544/27999591-828f328e-64e4-11e7-9d79-b8da475f33dc.png)

**Comment by tokman2** [comment]
I have the same issue. I can download the patch from other source is there a way console command to use that?

**Comment by Lisanne27** [comment]
Same issue, downloaded Mapleseed 2.1.1.15 and now the only updates available to BotW are v16 and v33. I was at v97 beforehand.

**Comment by Tsume** [comment]
Added a custom set option in the recent hotfix.
https://github.com/Tsume/Maple-Tree/releases/tag/v2.1.1.15-hf1

**Comment by KathrynCrawford** [comment]
Thanks Tsume. You're awesome.
