### ISSUE TITLE
It doesn't pop up

### ISSUE THREAD

**Issue by metalgta** [Tsume/Maple-Tree#85]
When I chose the two folders the first time i use mapleseed2 (games folder and cemu file) the program doesn't pop up. It doesn't appear any window...why? i'm on win10 and execute like administrator. i also cancel its folder from appdata but nothing changed﻿

Tried to restart, but nothing changed...i also disabled windows firewall but nada. It seems there is something that stop the launch of the program, in fact the window, in which it is, changes colour (how if it passes in backgroud, but after few second it returns foreground)﻿ and the .exe is killed alone in task manager

**Comment by Tsume** [comment]
Read the FAQ here:
https://github.com/Tsume/Maple-Tree
