### ISSUE TITLE
Error when started

### ISSUE THREAD

**Issue by podamask** [Tsume/Maple-Tree#88]
When started crushing with "The tool requires an Internet connection for network features". I turned off antivirus and agreed connection in windows firewall.

System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: source
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в MapleLib.Databases.WiiuTitleDatabase.WiiUTitleKeys() в E:\Projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:строка 207
   в MapleLib.Databases.WiiuTitleDatabase.<>c__DisplayClass16_0.<Create>b__0() в E:\Projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:строка 101
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MapleLib.Databases.WiiuTitleDatabase.<Create>d__16.MoveNext() в E:\Projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:строка 100
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MapleLib.Databases.WiiuTitleDatabase.<InitDatabase>d__14.MoveNext() в E:\Projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:строка 60
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Tsume** [comment]
Make sure you can access this http://wiiu.titlekeys.gq/ using your browser

**Comment by podamask** [comment]
I can access this site using my browser, but "Maple-Tree" still asking internet connection.
http://prntscr.com/fzmtyf

**Comment by Tsume** [comment]
The only reason you would get that error is if you're unable to access http://www.google.com/ or something is still blocking the programs access to the internet.

**Comment by podamask** [comment]
Need insert something here?
http://prntscr.com/fzob5d

**Comment by Tsume** [comment]
The first box is for content title ID, the 2nd box is for the version if you don't want the latest.

**Comment by podamask** [comment]
Version 1.1.0.53 is working fine. Thank you.
http://prntscr.com/fzolfu
