### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Virallata** [Tsume/Maple-Tree#89]
Hello, i am in Windows 10, and using Adm for open de app, but i got this error

> System.Collections.Generic.KeyNotFoundException: A chave fornecida não estava presente no dicionário.
   em System.ThrowHelper.ThrowKeyNotFoundException()
   em System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   em LiteDB.IndexService.<FindAll>d__13.MoveNext()
   em LiteDB.CollectionService.Drop(CollectionPage col)
   em LiteDB.LiteEngine.<>c__DisplayClass45_0.<DropCollection>b__0(CollectionPage col)
   em LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   em MapleLib.Databases.WiiuTitleDatabase.<InitDatabase>d__14.MoveNext() na E:\Projects\MapleTree\MapleLib\Databases\WiiuTitleDatabase.cs:linha 58
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   em System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Virallata** [comment]
I deleted the Mappletree forlder and got this one:

> System.Windows.Markup.XamlParseException: A invocação do construtor no tipo 'MapleCake.ViewModels.MainWindowViewModel' que corresponde às restrições de associação especificadas iniciou uma exceção. ---> System.TypeInitializationException: O inicializador de tipo de 'MapleLib.Database' acionou uma exceção. ---> System.IO.IOException: O processo não pode acessar o arquivo 'C:\Users\BB8\AppData\Roaming\MapleTree\mapleseed.db' porque ele está sendo usado por outro processo.
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   em MapleLib.Common.Helper.FileOpenStream(String path) na E:\Projects\MapleTree\MapleLib\Common\Helper.cs:linha 67
   em MapleLib.Database..cctor() na E:\Projects\MapleTree\MapleLib\Database.cs:linha 28
   --- Fim do rastreamento de pilha de exceções internas ---
   em MapleLib.Database.RegisterEvent(EventHandler`1 onEvent)
   em MapleCake.ViewModels.MainWindowViewModel.RegisterEvents()
   em MapleCake.ViewModels.MainWindowViewModel.Init()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   em System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   em System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   em System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   em System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   em System.Windows.Application.DoStartup()
   em System.Windows.Application.<.ctor>b__1_0(Object unused)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.DispatcherOperation.InvokeImpl()
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Windows.Threading.DispatcherOperation.Invoke()
   em System.Windows.Threading.Dispatcher.ProcessQueue()
   em System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   em MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em System.Windows.Application.RunDispatcher(Object ignore)
   em System.Windows.Application.RunInternal(Window window)
   em MapleCake.App.Main()

**Comment by Tsume** [comment]
Check your processes and make sure MapleSeed2 isn't running in the background.

Manually delete C:\Users\BB8\AppData\Roaming\MapleTree\mapleseed.db
