### ISSUE TITLE
Update Not Working?

### ISSUE THREAD

**Issue by theboy181** [Tsume/Maple-Tree#9]
I'm unsure if its working as it should. The update is greyed out.

Also I started Child of Light by clicking play, and it loaded full screen and it was black. I was unable to exit full screen or quit the Emulator without Ctrl-Alt-Del

**Comment by Tsume** [comment]
Update hasn't been implemented yet so that's normal. I think the freezing is a random bug with cemu that occurs when loading the cached shaders. Does it happen repeatedly or sporadically?

**Comment by Tsume** [comment]
Fixed.
